### ISSUE TITLE
Bazel build broken

### ISSUE THREAD

**Issue by jart** [google/highwayhash#36]
When exporting to GitHub, the `third_party/highwayhash/` prefix should be stripped from include lines so they become relative to the root of the repository. Otherwise I get errors like this:

```
external/highwayhash/highwayhash/sip_hash.cc:15:10: fatal error: 'third_party/highwayhash/highwayhash/sip_hash.h' file not found
#include "third_party/highwayhash/highwayhash/sip_hash.h"
         ^
```

**Comment by vks** [comment]
This is intentional behavior introduced in 44f30a28f870cd8e82db7440bd77028935fb8f4d. See #27 for more background. The workaround is to put the directory of the git clone into `third_party/highwayhash` subdirectories.

**Comment by jart** [comment]
I wrote https://github.com/google/highwayhash/commit/44f30a28f870cd8e82db7440bd77028935fb8f4d and it's not what I intended :)

**Comment by vks** [comment]
Huh, I did not know that, sorry. I thought it was intentional because of @jan-wassenberg's comments in #27:

> FYI we had to change the include paths because -isystem is quite costly for Bazel. It would be nice if we can keep the source code the same internally and in Github.

> It is admittedly unusual - do you have an idea how we could keep the source code identical between the internal/external repository and avoid sed scripts in both directions? I suppose we could ```#define''' the header names, but that's also ugly.

I don't really see how to fix this without resorting to some sed scripts or changing bazel.

**Comment by jart** [comment]
There are two solutions to choose from:

1. `mkdir third_party && mv highwayhash third_party`
2. Use MOE or Copybara, which are pretty standard, and replace the includes on export / import.

**Comment by jart** [comment]
Also getting rid of -isystem flags (the includes attribute in BUILD) is why I did it. But in order for it to work, the include paths in the repository need to be relative to the root of the repository.

**Comment by jan-wassenberg** [comment]
Thanks for your comments, looks like option 2 is less painful in the long term.
I'm leaning towards MOE (more powerful than sed) and will be able to do this in a few days.

**Comment by jart** [comment]
Feel free to mail me the CL making the MOe configuration change. I'll be happy to review.

**Comment by jan-wassenberg** [comment]
Thanks, will do!

**Comment by jan-wassenberg** [comment]
Thank you for reviewing. MOE worked, the resulting huge commit is pushed.
This removes the third_party/highwayhash prefix, which I trust fixes the issue. If not, please feel free to reopen!

**Comment by jart** [comment]
Wonderful. Thank you @jan-wassenberg for all the work you put into unblocking an issue I'm trying to solve for @namrata-ibm.

**Comment by jart** [comment]
Where did the BUILD file go?

**Comment by jan-wassenberg** [comment]
Wasn't included in highwayhash_opensource_filegroup. I like your idea of a SipHash-specific BUILD file, but please let me know if you want the entire BUILD file back.
